### ISSUE TITLE
Зачем это все, если ты можешь пропсы деструктурировать из параметров и там же defaultValues указывать

### ISSUE THREAD

**Issue by r34son** [Arillaxe/arkanyx-webapp#1]
https://github.com/Arillaxe/arkanyx-webapp/blob/a96bb9dedf503d5707d9432cdf5d4332437ef082/src/components/Button/Button.jsx#L19

**Comment by Arillaxe** [comment]
@r34son линтер говорит что так не принято

**Comment by Arillaxe** [comment]
@r34son best practise типо
